# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-NEXUS
version:      0.68
version_from: lib/Bio/NEXUS.pm
installdirs:  site
requires:
    Clone::PP:                     1.02
    Test::Deep:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
